# Generated by Django 5.0.8 on 2025-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='text',
            field=models.TextField(blank=True, help_text='Features for pricing, seperted by new line', null=True),
        ),
    ]
