# Generated by Django 5.0.8 on 2025-02-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_subscription_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='text',
            new_name='features',
        ),
    ]
