# Generated by Django 5.0.8 on 2025-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_remove_usersubscription_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
