# Generated by Django 5.0.8 on 2025-03-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvdocument',
            name='title',
        ),
    ]
