# Generated by Django 5.0.8 on 2025-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_generatedcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcv',
            name='file',
            field=models.TextField(),
        ),
    ]
