# Generated by Django 5.0.8 on 2025-05-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_generatedcv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcv',
            name='job_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
