# Generated by Django 5.0.8 on 2025-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_generatedcv_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcv',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
