# Generated by Django 5.0.8 on 2025-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_generatedcv_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcv',
            name='job_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
