# Generated by Django 5.0.8 on 2025-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_generatedcv_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='plain_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
